<div id="radio-page-customize" class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded-strong ">

    <h2 style="float:left"><?php echo _("Customize Your Radio Page") ?></h2>
    <div style="clear:both"></div>

    <form method="post" id="radio_page_customize_form" enctype="multipart/form-data">
        <div style="clear:both"></div>
        <?php echo $this->form; ?>

    </form>

</div>
