.bottom_bar .play {
    background-color: <?php echo $this->widgetColour?>;
}

.bottom_bar .pause {
    background-color: <?php echo $this->widgetColour?>;
}

.bottom_bar .cont_btn:hover {
    background-color: rgba(<?php echo $this->widgetColourRgb["r"]?>,
                            <?php echo $this->widgetColourRgb["g"]?>,
                            <?php echo $this->widgetColourRgb["b"]?>, 0.9);
}